import turtle
turtle.Screen().bgcolor("Pink")
turtle.Screen().title("Square")
square=turtle.Turtle()
for i in range(4):
    square.forward(200)
    square.right(90)
square.penup()
square.left(90)
square.fd(100)
square.pendown()
square.fd(100)
square.left(90)
square.fd(100)
square.left(90)
square.fd(100)
square.left(90)
square.fd(100)
square.left(90)
square.penup()
square.fd(100)
square.left(90)
square.pendown()
for i in range(4):
    square.fd(100)
    square.left(90)
square.write("I did a square 3 times!")
turtle.done()